### ISSUE TITLE
Support "grouped by sort" in multi-line view

### ISSUE THREAD

**Issue by Betterbird** [Betterbird/thunderbird-patches#23]
Requested in https://www.thunderbird-mail.de/forum/thread/88729-betterbird-gruppiert-nach-sortierung-in-virtuellen-ordnern-nicht-m%C3%B6glich/

**Comment by yoshimo** [comment]
A good idea to see a nice thread-view is https://github.com/thunderbird-conversations/thunderbird-conversations .

**Comment by Betterbird** [comment]
Supporting multi-line in a threaded view doesn't make sense, it would look like this:

![Threading-multi-line](https://user-images.githubusercontent.com/86832723/147838415-7e9694fe-6e54-469e-8e56-44ace98e16e8.png)

It's bad enough in a "grouped by sort view", but there we can move the threading to the column being sorted, which looks like this:

![image](https://user-images.githubusercontent.com/86832723/147838464-31a78e2f-2e1a-4508-916a-c6ecacc57446.png)

Even there you can get into ugly situations if you sort/group by correspondent or subject:

![image](https://user-images.githubusercontent.com/86832723/147838492-d973759f-8b64-4f39-8a84-3077dd4dc104.png)
![image](https://user-images.githubusercontent.com/86832723/147838509-168c4266-0ae0-4162-8ea0-84680a2599f1.png)

This is now mostly implemented with:
https://github.com/Betterbird/thunderbird-patches/commit/0213183e7f53fe085bac9a18aa190a0238ac5a65
https://github.com/Betterbird/thunderbird-patches/commit/733174d3376d35858ce2db9673ce51698dc94926
and one more to come.

**Comment by Betterbird** [comment]
We've just implemented treading for multi-line views. So far it's only shipping in BB 102 "preview", but we'll backport it to 91.12 at the and of July. We could also do a "latest build" version with this included.

**Comment by qazip** [comment]
This is still not available in 91.13, or am I doing something wrong?

**Comment by qazip** [comment]
> We've just implemented treading for multi-line views. So far it's only shipping in BB 102 "preview", but we'll backport it to 91.12 at the and of July. We could also do a "latest build" version with this included.

This is still not available in 91.13, or am I doing something wrong?

**Comment by Betterbird** [comment]
We're talking about threading for multi-line views? That's working since BB 91.12:
![image](https://user-images.githubusercontent.com/86832723/186400126-a9dd2adb-517e-4774-8848-c56eb4a523ed.png)
