### ISSUE TITLE
E-mail sending failed on version 128.6.1esr-bb21 (64-bit) with `addr.name is undefined` error when using OWL due to backport of TB bug 1900211.

### ISSUE THREAD

**Issue by DutchFlander** [Betterbird/thunderbird-patches#404]
Hi,

Issue:
E-mail sending fails with the following error message:
Sending of the message failed.
addr.name is undefined

![Image](https://github.com/user-attachments/assets/f894a723-6fda-43d3-8cd3-16a13adf409e)

The mail is properly addressed, and can be sent in any earlier version of BB.

Version used: 
128.6.1esr-bb21 (64-bit) via flatpak

System details:
Debian 12
Kernel: 6.12.9-amd64 (64-bit)
KDE Plasma 6.2.5 Wayland

For office365 exchange compatibility Owl for Exchange addon is used.

The same issue is not present on Thunderbird and reverting the BB to (any) earlier version, the issue is not present.
Version 128.6.0esr-bb20 (64-bit) is the last version where any mail can be sent without any error message.

The issue can be reproduced anytime, if logs/traces are needed, I can provide them, just let me know what is needed.

Thanks in advance,
Dutch

**Comment by Betterbird** [comment]
The `addr.name[https://addr.name]` error comes from integrating this 
patch that the TB folks implemented:

https://github.com/Betterbird/thunderbird-patches/blob/main/128/bugs/1900211-dont-collect-ml-post-via-addr.patch

You're sending to a "plain" address ***@***.***` without display name? 
Shouldn't happen with sending to `Donald ***@***.***>`.

Hard to believe that that wasn't found in testing. Maybe just related to 
OWL?

**Comment by Betterbird** [comment]
Sorry for the badly formatted reply via email. And sorry for over-zealously closing your Issue #403, it really looked like one of those "same old, same old, can't send after upgrade" issues. It didn't mention neither Linux nor due `addr.name` error.

Whilst the patch we integrated isn't ideal on second inspection, it doesn't cause any issues when sending to addresses with or without display part, tested just now. Given that neither works for you, it's likely an issue in OWL.

We can make a "latest build" version with the potential issue fixed, but you won't get that as FlatPak.

**Comment by Betterbird** [comment]
If you can run a Linux version from .tar.bz2, I can make one for you.

**Comment by Betterbird** [comment]
Hold on, do you have some faulty self-CC or self-BCC configured?

**Comment by Betterbird** [comment]
Another user can reproduce it with OWL. Without OWL, it's not an issue.

**Comment by benbucksch** [comment]
We will look at it. CC @neilrashbrook

**Comment by Betterbird** [comment]
Here's a Windows version that should fix this:
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-128.6.1esr-bb21-latest-build.en-US.win64.installer.exe

**Comment by Betterbird** [comment]
> We will look at it. CC [@NeilRashbrook](https://github.com/NeilRashbrook)

Already fixed in BB: https://github.com/Betterbird/thunderbird-patches/blob/main/128/bugs/1900211-follup-up.patch (despite the bad patch name).

**Comment by benbucksch** [comment]
Thanks.
The problem still exists in TB, right? Which TB release is this patch planned for?

**Comment by benbucksch** [comment]
TB upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1900211

So, this landed in TB 135 beta, and they intend to manually backport it to TB 128.
I've attached your patch to that bug. Surely they'll refuse it, because it's not in phabricator. :-(

**Comment by DutchFlander** [comment]
> Another user can reproduce it with OWL. Without OWL, it's not an issue.

This means I should stick with 128.6.0esr-bb20 (64-bit) until OWL fixes the issue, or this is something that the next BB release can handle with the same OWL version?

**Comment by Betterbird** [comment]
As we wrote in https://github.com/Betterbird/thunderbird-patches/issues/404#issuecomment-2616846859, we can make a .tar.bz2 if you can use that.

**Comment by Betterbird** [comment]
Here's a .tar.bz2 for Linux:
https://www.betterbird.eu/downloads/LinuxArchive/betterbird-128.6.1esr-bb21-latest-build.en-US.linux-x86_64.tar.bz2

**Comment by DutchFlander** [comment]
> Here's a .tar.bz2 for Linux: https://www.betterbird.eu/downloads/LinuxArchive/betterbird-128.6.1esr-bb21-latest-build.en-US.linux-x86_64.tar.bz2

I'll try it out and use it until a new version is released, but for the time being it will be confusing, because the version numbering is the same, but I guess, this is just a small testing modification of the same:
![Image](https://github.com/user-attachments/assets/3555eb1f-592d-4290-9076-afd9c5a4263d)

**Comment by Betterbird** [comment]
Well, in each software additional to the version number there is a build ID. And that is different. We can't release a hole bunch of binaries on three platforms, AUR, FlatPak, winget, Chocolatey, etc. You can always downgrade to the previous version and wait until it's fixed in the next release on 4th March 2025.

**Comment by DutchFlander** [comment]
Understood.
Thanks for the clarification and the help.

**Comment by sf985** [comment]
Thank you for pointing me here! I am a Linux newbie, so I just wonder what happens if I install Betterbird through the tarball linked above when I already have a flatpak installation? I don't want to uninstall the flatpak because my accounts and settings are then also removed(?). I understand this question might be off-topic, but grateful for any answer.

**Comment by Betterbird** [comment]
Profiles are never removed upon uninstallation. However, the FlatPak version stored the profile elsewhere, so it's a little hard to switch between the two:
https://github.com/flathub/eu.betterbird.Betterbird/?tab=readme-ov-file#migration-from-pre-exisiting-installations

You could downgrade your FlatPak to 128.6.0 or wait for the official fix next week (Tue/Wed) in 128.7.0.

**Comment by sf985** [comment]
Thank you so much for the responses, and at speed at that! Much appreciated.
